/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package scratchcards

import java.io.File
import kotlin.math.pow

fun readFile(fileName: String): List<String> {
    val currentDir = System.getProperty("user.dir")
    val file: File = File("$currentDir/src/main/resources/$fileName")
    return file.bufferedReader().readLines()
}

fun computeWorthOfScratchcards(cards: List<String>): Int {
    var total: Int = 0
    val regex: Regex = Regex("Card\\s+\\d+:")
    val r: Regex = Regex("\\d+")
    for (card in cards) {
        val array: Array<String> = card.replace(regex, "").split("|").toTypedArray()
        val matchesOfWinningNumbers = r.findAll(array[0])
        val matchesOfActualNumbers = r.findAll(array[1])
        val winningNumbers: Set<Int> = matchesOfWinningNumbers.toList().map { it.value.toInt() }.toSet()
        val actualNumbers: Set<Int> = matchesOfActualNumbers.toList().map { it.value.toInt() }.toSet()
        val n: Int = winningNumbers.intersect(actualNumbers).size
        if (n > 0) {
            total += (2.0).pow(n - 1).toInt()
        }
    }
    return total
}


fun main() {
    val input: List<String> = readFile("input.txt")
    val points: Int = computeWorthOfScratchcards(input)
    println("Total points are: $points")
}
