/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package trebuchet

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.whatFloor("()"), "app should have a greeting")
        assertNotNull(classUnderTest.findPosition("()"), "app should have a greeting")
    }
}